apiVersion: v1
kind: Namespace
metadata:
  name: storage-measurer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-measurer
  namespace: storage-measurer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-measurer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: storage-measurer
  namespace: storage-measurer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storage-measurer
  namespace: storage-measurer
  labels:
    app.kubernetes.io/name: storage-measurer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storage-measurer
    spec:
      containers:
      - image: giorio94/liqo-storage-measurer:v0.1.5
        imagePullPolicy: IfNotPresent
        name: storage-measurer
        args:
        - --namespace=storage-benchmark
        - --replicas=__REPLICAS__
        - --storage-class=liqo
        - --v=2
      dnsPolicy: Default
      restartPolicy: OnFailure
      serviceAccountName: storage-measurer
